name: Test and Prebuild
on: [push]
jobs:
  build-test:
    #runs-on: macos-11
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: npm test
  prebuild:
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-16.04
      steps:
      - run: npm run prebuild
      - run: tar -cvf prebuild-darwin.tar prebuilds
      - run: hexdump "prebuilds/darwin-x64/node.abi93.node" | head -10
      - name: Prebuild
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: prebuild-darwin.tar
