name: Test and Prebuild
on: [push]
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - run: npm run prebuild
      - run: tar -cvf prebuild-darwin-x86.tar prebuilds
      - name: Prebuild
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilds/**
      - run: hexdump "prebuilds/darwin-x64/node.abi93.node" | head -10
