name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - run: npm run prebuild
      - run: tar --create --verbose --file="$ARCHIVE_NAME" --directory prebuilds
        env:
          ARCHIVE_NAME: $GITHUB_REF-$RUNNER_OS-x86.tar
      - name: Prebuild
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilds/**
      - run: hexdump "prebuilds/darwin-x64/node.abi83.node" | head -10
