name: Test Install
on: 
  workflow_dispatch:

jobs:
  test-arm7:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          install: |
            apt-get update
            apt-get install -y curl libatomic1 python3
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 16
            node -v
            npm install -g mocha node-gyp
          run: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            node -v
            npm install --ignore-scripts
            mocha test/**.test.js --recursive && npm run test:types
            node-gyp rebuild
            echo "$(which node) and $(which node-gyp)"
            npm install lmdb --ignore-scripts --verbose
